branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

sudo: required

matrix:
  fast_finish: true

stages:
  - name: tests
  - name: release

install:
  - pip install --upgrade pip
  - pip install codecov tox
script:
  - make patch
  - cd superset
  - tox
after_success:
  - codecov

jobs:
  include:
    - language: python
      python: 3.6
      env: TOXENV=py36-mysql
      services:
        - mysql
        - redis-server
      before_script:
        - mysql -u root -e "DROP DATABASE IF EXISTS superset; CREATE DATABASE superset DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci"
        - mysql -u root -e "CREATE USER 'mysqluser'@'localhost' IDENTIFIED BY 'mysqluserpassword';"
        - mysql -u root -e "GRANT ALL ON superset.* TO 'mysqluser'@'localhost';"
    - language: python
      env: TOXENV=javascript
      before_install:
        - nvm install 10.14.2
    - language: python
      python: 3.6
      env: TOXENV=flake8
    - language: python
      python: 3.6
      env: TOXENV=py36-sqlite
      services:
        - redis-server
    - language: python
      python: 3.6
      env: TOXENV=py36-postgres
      services:
        - postgres
        - redis-server
      before_script:
        - psql -U postgres -c "CREATE DATABASE superset;"
        - psql -U postgres -c "CREATE USER postgresuser WITH PASSWORD 'pguserpassword';"
    - language: python
      python: 3.6
      env: TOXENV=pylint
    - stage: release
      name: 'Release to Docker Hub'
      services:
        - docker
      script:
        - echo make superset-docker-push-latest-release
